name = "UnitDistanceGraphs"
version = "0.1.0"
defaultTargets = ["UnitDistanceGraphs"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "master"

[[lean_lib]]
name = "UnitDistanceGraphs"
