/-
# Følner sequences for discrete groups (abstract, reusable)

This file develops the amenability input needed by [M23] Theorem 1 in the form actually used there:
a finitely generated **solvable** group (here, the group generated by the congruences of a finite
plane graph, a subgroup of the solvable group `Isom(ℝ²)`) satisfies the **Følner condition**.

[M23] obtain this abstractly ("solvable ⇒ amenable ⇒ Følner property", cited). We formalize that
chain constructively at the level of finite sets:

* `FolnerCond` — every finite set of elements and `ε > 0` admit a nonempty finite set that is
  `ε`-invariant under each of them.
* (extension lemma) the Følner condition for `G` from ones for a normal subgroup and the quotient.
* (base case) abelian groups satisfy the Følner condition.
* (assembly) solvable groups satisfy the Følner condition (`folnerCond_of_isSolvable`).

The `Finset`-valued formulation matches the averaging in `FirstBlowUp.lean` (`ratio`,
right-translation by the congruence realizers). It is deliberately self-contained and group-generic,
so it can be reused / upstreamed.
-/

import Mathlib

namespace UnitDistanceGraphs.Folner

open Filter Topology
open scoped Classical Pointwise

variable {Γ : Type*} [Group Γ]

/-- The one-sided **right Følner ratio** of a group element `g` relative to a finite set `S`:
`|S·g \ S| / |S|`. The set `S` is approximately right-invariant under `g` when this is small. -/
noncomputable def ratio (g : Γ) (S : Finset Γ) : ℝ :=
  (((S.image (· * g)) \ S).card : ℝ) / (S.card : ℝ)

/-! ### Foundational facts about `ratio` -/

/-- Right multiplication by `g` preserves cardinality. -/
@[simp] lemma card_image_mul_right (g : Γ) (S : Finset Γ) :
    (S.image (· * g)).card = S.card :=
  Finset.card_image_of_injective _ (mul_left_injective g)

/-- The two set-differences of `S` and its right-translate have equal cardinality (both sets have
`|S|` elements), so the two-sided symmetric-difference ratio is exactly twice `ratio`. -/
lemma card_sdiff_image_mul_comm (g : Γ) (S : Finset Γ) :
    (S \ S.image (· * g)).card = (S.image (· * g) \ S).card :=
  Finset.card_sdiff_comm (card_image_mul_right g S).symm

/-- The full two-sided symmetric-difference ratio, `(|S \ S·g| + |S·g \ S|)/|S|`, equals `2·ratio`.
This is the quantity consumed by the averaging estimate in `FirstBlowUp.lean`. -/
lemma twoSided_eq (g : Γ) (S : Finset Γ) :
    (((S \ S.image (· * g)).card + (S.image (· * g) \ S).card : ℝ)) / (S.card : ℝ)
      = 2 * ratio g S := by
  rw [card_sdiff_image_mul_comm]
  unfold ratio
  ring

/-! ### The (left) Følner condition and closure under extensions

We develop amenability in the **Reiter/Følner-condition** form (`FolnerCond`): every finite set of
elements admits an arbitrarily invariant nonempty finite set. Using *left* translation and the
transversal-times-kernel construction, closure under group extensions avoids the conjugation
difficulty, and the finitely many twists are absorbed by choosing the kernel-Følner set last. -/

/-- The **left** Følner ratio `|g·S \ S| / |S|`. -/
noncomputable def lratio (g : Γ) (S : Finset Γ) : ℝ :=
  (((S.image (g * ·)) \ S).card : ℝ) / (S.card : ℝ)

/-- **Left–right bridge.** The right ratio of `g` on `S⁻¹` equals the left ratio of `g⁻¹` on `S`.
This converts the (left) Følner condition into the right `ratio` used by the averaging. -/
lemma ratio_inv (g : Γ) (S : Finset Γ) : ratio g S⁻¹ = lratio g⁻¹ S := by
  have hset : S⁻¹.image (· * g) = (S.image (g⁻¹ * ·))⁻¹ := by
    rw [Finset.inv_def, Finset.image_image, Finset.inv_def, Finset.image_image]
    exact Finset.image_congr fun s _ => by simp only [Function.comp_apply]; group
  have hsdiff : (S.image (g⁻¹ * ·))⁻¹ \ S⁻¹ = (S.image (g⁻¹ * ·) \ S)⁻¹ := by
    rw [Finset.inv_def, Finset.inv_def, Finset.inv_def]
    ext y; simp only [Finset.mem_sdiff, Finset.mem_image]
    constructor
    · rintro ⟨⟨x, hx, rfl⟩, hn⟩
      exact ⟨x, ⟨hx, fun h => hn ⟨x, h, rfl⟩⟩, rfl⟩
    · rintro ⟨x, ⟨hx, hnx⟩, rfl⟩
      exact ⟨⟨x, hx, rfl⟩, fun ⟨z, hz, hzy⟩ => hnx (inv_injective hzy ▸ hz)⟩
  unfold ratio lratio
  rw [hset, hsdiff, Finset.card_inv, Finset.card_inv]

variable (Γ) in
/-- The **Følner condition** for `Γ` (amenability, Reiter/Følner form): for every finite set `K` of
elements and every `ε > 0` there is a nonempty finite `F` that is `ε`-invariant under left
translation by each `g ∈ K`. -/
def FolnerCond : Prop :=
  ∀ (K : Finset Γ) {ε : ℝ}, 0 < ε → ∃ F : Finset Γ, F.Nonempty ∧ ∀ g ∈ K, lratio g F < ε

/-- Transporting `lratio` along an injective group homomorphism: the ratio computed in a subgroup
`H` equals the ratio in `Γ` of the image set. -/
lemma lratio_map {H : Type*} [Group H] (ι : H →* Γ) (hι : Function.Injective ι)
    (h : H) (S : Finset H) :
    lratio (ι h) (S.map ⟨ι, hι⟩) = lratio h S := by
  have himg : (S.map ⟨ι, hι⟩).image (ι h * ·) = (S.image (h * ·)).map ⟨ι, hι⟩ := by
    rw [Finset.map_eq_image, Finset.map_eq_image, Finset.image_image, Finset.image_image]
    exact Finset.image_congr (fun x _ => (ι.map_mul h x).symm)
  unfold lratio
  rw [himg, ← Finset.map_sdiff, Finset.card_map, Finset.card_map]

/-- **Amenability is closed under extensions** (Følner-condition form). If the kernel `N = ker π`
and the quotient `Q` both satisfy the Følner condition, so does `G`. The extension Følner set is
`σ(D)·E` for a section `σ`, a `Q`-Følner set `D`, and a kernel-Følner set `E` chosen *after* `D` to
absorb the finitely many twists — which, thanks to the left-translation form, are genuine kernel
translations (no conjugation). -/
theorem folnerCond_of_extension {G Q : Type*} [Group G] [Group Q]
    (π : G →* Q) (hπ : Function.Surjective π)
    (hN : FolnerCond π.ker) (hQ : FolnerCond Q) : FolnerCond G := by
  classical
  letI : DecidableEq (↥π.ker) := Classical.decEq _
  intro K ε hε
  -- a set-section of `π`
  set σ : Q → G := Function.invFun π with hσdef
  have hσ : ∀ q, π (σ q) = q := fun q => Function.invFun_eq (hπ q)
  set ε' : ℝ := ε / 3 with hε'def
  have hε' : 0 < ε' := by positivity
  -- `Q`-Følner set, invariant under left translation by every `π g`, `g ∈ K`
  obtain ⟨D, hDne, hD⟩ := hQ (K.image π) hε'
  -- the twist of `(d, g)` into the kernel: `σ(πg·d)⁻¹ · g · σ d`
  let tw : Q → G → π.ker := fun d g => ⟨(σ (π g * d))⁻¹ * g * σ d, by
    simp only [MonoidHom.mem_ker, map_mul, map_inv, hσ]; group⟩
  -- kernel-Følner set, invariant under the (finitely many) twists
  set SN : Finset π.ker := (D ×ˢ K).image (fun p => tw p.1 p.2) with hSNdef
  obtain ⟨E, hEne, hE⟩ := hN SN hε'
  -- the extension Følner set `σ(D)·E`
  set Φ : Q × π.ker → G := fun p => σ p.1 * (p.2 : G) with hΦdef
  set F : Finset G := (D ×ˢ E).image Φ with hFdef
  refine ⟨F, (hDne.product hEne).image _, ?_⟩
  intro g hg
  -- `Φ` is injective, so `|F| = |D|·|E|`
  have hΦinj : Function.Injective Φ := by
    intro p q hpq
    have h1 : p.1 = q.1 := by
      have hπ' := congrArg π hpq
      simp only [hΦdef, map_mul, hσ, MonoidHom.mem_ker.mp p.2.property,
        MonoidHom.mem_ker.mp q.2.property, mul_one] at hπ'
      exact hπ'
    have h2 : (p.2 : G) = (q.2 : G) := by
      simp only [hΦdef, h1] at hpq; exact mul_left_cancel hpq
    exact Prod.ext h1 (Subtype.ext h2)
  have hFcard : F.card = D.card * E.card := by
    rw [hFdef, Finset.card_image_of_injective _ hΦinj, Finset.card_product]
  have hDpos : 0 < (D.card : ℝ) := by exact_mod_cast hDne.card_pos
  have hEpos : 0 < (E.card : ℝ) := by exact_mod_cast hEne.card_pos
  have hFpos : 0 < (F.card : ℝ) := by rw [hFcard]; push_cast; positivity
  -- **Core counting bound** (the transversal/kernel decomposition): the `Q`-boundary contributes
  -- `≤ ε'·|D|·|E|` and the kernel-boundary `≤ |D|·ε'·|E|`.
  have hnum : ((F.image (g * ·) \ F).card : ℝ) ≤ 2 * ε' * ((D.card : ℝ) * E.card) := by
    -- reparametrise: `g·Φ(d,e) = Φ(πg·d, tw d g · e)`, so the boundary maps through `Φ`
    set ψ : Q × π.ker → Q × π.ker := fun p => (π g * p.1, tw p.1 g * p.2) with hψdef
    have hgΦ : ∀ p : Q × π.ker, g * Φ p = Φ (ψ p) := by
      intro p
      have htw : σ (π g * p.1) * ((tw p.1 g : π.ker) : G) = g * σ p.1 := by
        show σ (π g * p.1) * ((σ (π g * p.1))⁻¹ * g * σ p.1) = g * σ p.1
        group
      show g * (σ p.1 * (p.2 : G)) = σ (π g * p.1) * ((tw p.1 g * p.2 : π.ker) : G)
      rw [Subgroup.coe_mul, ← mul_assoc (σ (π g * p.1)), htw, mul_assoc]
    have himg : F.image (g * ·) = ((D ×ˢ E).image ψ).image Φ := by
      rw [hFdef, Finset.image_image, Finset.image_image]
      exact Finset.image_congr fun p _ => hgΦ p
    -- `Φ` injective ⇒ the boundary count descends to `Q × ker`
    have hsdiff : ((D ×ˢ E).image ψ).image Φ \ (D ×ˢ E).image Φ
        = (((D ×ˢ E).image ψ) \ (D ×ˢ E)).image Φ := by
      ext x
      simp only [Finset.mem_sdiff, Finset.mem_image]
      constructor
      · rintro ⟨⟨a, ha, rfl⟩, hx⟩
        exact ⟨a, ⟨ha, fun hb => hx ⟨a, hb, rfl⟩⟩, rfl⟩
      · rintro ⟨a, ⟨ha, hna⟩, rfl⟩
        exact ⟨⟨a, ha, rfl⟩, fun ⟨b, hb, hbx⟩ => hna (hΦinj hbx ▸ hb)⟩
    rw [himg, hFdef, hsdiff, Finset.card_image_of_injective _ hΦinj]
    -- cover the boundary by the two "bad" filters
    have hsub : (((D ×ˢ E).image ψ) \ (D ×ˢ E))
        ⊆ ((D ×ˢ E).filter (fun p => π g * p.1 ∉ D ∨ tw p.1 g * p.2 ∉ E)).image ψ := by
      intro x hx
      rw [Finset.mem_sdiff] at hx
      obtain ⟨hxi, hxn⟩ := hx
      rw [Finset.mem_image] at hxi
      obtain ⟨p, hp, rfl⟩ := hxi
      rw [Finset.mem_image]
      refine ⟨p, Finset.mem_filter.mpr ⟨hp, ?_⟩, rfl⟩
      by_contra hcon
      push Not at hcon
      exact hxn (Finset.mem_product.mpr ⟨hcon.1, hcon.2⟩)
    have hsplit : ((D ×ˢ E).filter (fun p => π g * p.1 ∉ D ∨ tw p.1 g * p.2 ∉ E)).card
        ≤ ((D ×ˢ E).filter (fun p => π g * p.1 ∉ D)).card
          + ((D ×ˢ E).filter (fun p => tw p.1 g * p.2 ∉ E)).card := by
      rw [Finset.filter_or]; exact Finset.card_union_le _ _
    -- bound filter₁: condition on `p.1` only, so it is a product
    have hf1 : ((D ×ˢ E).filter (fun p => π g * p.1 ∉ D)).card
        ≤ (D.image (π g * ·) \ D).card * E.card := by
      have hfe : (D ×ˢ E).filter (fun p => π g * p.1 ∉ D)
          = (D.filter (fun d => π g * d ∉ D)) ×ˢ E := by
        ext ⟨d, e⟩; simp only [Finset.mem_filter, Finset.mem_product]; tauto
      rw [hfe, Finset.card_product]
      refine Nat.mul_le_mul_right _ ?_
      rw [← Finset.card_image_of_injective (D.filter _) (mul_right_injective (π g))]
      refine Finset.card_le_card fun q hq => ?_
      rw [Finset.mem_image] at hq
      obtain ⟨d, hd, rfl⟩ := hq
      rw [Finset.mem_filter] at hd
      exact Finset.mem_sdiff.mpr ⟨Finset.mem_image_of_mem _ hd.1, hd.2⟩
    -- bound filter₂: fibrewise over `p.1`
    have hf2 : (((D ×ˢ E).filter (fun p => tw p.1 g * p.2 ∉ E)).card : ℝ)
        ≤ (D.card : ℝ) * (ε' * E.card) := by
      rw [Finset.card_eq_sum_card_fiberwise (f := Prod.fst) (t := D)
        (fun p hp => (Finset.mem_product.mp (Finset.filter_subset _ _ hp)).1)]
      push_cast
      refine le_trans (Finset.sum_le_sum (g := fun _ => ε' * (E.card : ℝ)) fun d hd => ?_)
        (le_of_eq (by rw [Finset.sum_const, nsmul_eq_mul]))
      -- per-`d` bound via the injection `p ↦ tw d g · p.2` into `E·(tw d g) \ E`
      have hE' := hE (tw d g)
        (Finset.mem_image.mpr ⟨(d, g), Finset.mem_product.mpr ⟨hd, hg⟩, rfl⟩)
      rw [lratio, div_lt_iff₀ hEpos] at hE'
      -- pin the target sdiff to `hE'`'s term (same `DecidableEq` instance), then inject the fiber
      refine le_trans (Nat.cast_le.mpr (Finset.card_le_card_of_injOn
        (f := fun p => tw d g * p.2) (fun p hp => ?_) (fun a ha b hb hab => ?_))) (le_of_lt hE')
      · obtain ⟨hp1, hpd⟩ := Finset.mem_filter.mp hp
        obtain ⟨hp0, hpne⟩ := Finset.mem_filter.mp hp1
        exact Finset.mem_sdiff.mpr
          ⟨Finset.mem_image.mpr ⟨p.2, (Finset.mem_product.mp hp0).2, rfl⟩, hpd ▸ hpne⟩
      · rw [Finset.mem_coe] at ha hb
        exact Prod.ext ((Finset.mem_filter.mp ha).2.trans (Finset.mem_filter.mp hb).2.symm)
          (mul_right_injective (tw d g) hab)
    -- combine the two boundary bounds
    have hlt1 : ((D.image (π g * ·) \ D).card : ℝ) < ε' * D.card := by
      have := hD (π g) (Finset.mem_image.mpr ⟨g, hg, rfl⟩)
      rw [lratio, div_lt_iff₀ hDpos] at this; exact this
    have hstep1 : ((D ×ˢ E).image ψ \ (D ×ˢ E)).card
        ≤ ((D ×ˢ E).filter (fun p => π g * p.1 ∉ D ∨ tw p.1 g * p.2 ∉ E)).card :=
      le_trans (Finset.card_le_card hsub) Finset.card_image_le
    calc ((((D ×ˢ E).image ψ) \ (D ×ˢ E)).card : ℝ)
        ≤ (((D ×ˢ E).filter (fun p => π g * p.1 ∉ D ∨ tw p.1 g * p.2 ∉ E)).card : ℝ) := by
          exact_mod_cast hstep1
      _ ≤ (((D ×ˢ E).filter (fun p => π g * p.1 ∉ D)).card : ℝ)
            + (((D ×ˢ E).filter (fun p => tw p.1 g * p.2 ∉ E)).card : ℝ) := by exact_mod_cast hsplit
      _ ≤ (ε' * D.card) * E.card + (D.card : ℝ) * (ε' * E.card) := by
          refine add_le_add ?_ hf2
          calc (((D ×ˢ E).filter (fun p => π g * p.1 ∉ D)).card : ℝ)
              ≤ ((D.image (π g * ·) \ D).card : ℝ) * E.card := by exact_mod_cast hf1
            _ ≤ (ε' * D.card) * E.card :=
                mul_le_mul_of_nonneg_right (le_of_lt hlt1) (by positivity)
      _ = 2 * ε' * ((D.card : ℝ) * E.card) := by ring
  -- assemble: `lratio ≤ 2ε' = 2ε/3 < ε`
  have key : lratio g F ≤ 2 * ε' := by
    rw [lratio, div_le_iff₀ hFpos]
    calc ((F.image (g * ·) \ F).card : ℝ)
        ≤ 2 * ε' * ((D.card : ℝ) * E.card) := hnum
      _ = 2 * ε' * F.card := by rw [hFcard]; push_cast; ring
  have h2ε' : (2 : ℝ) * ε' < ε := by rw [hε'def]; linarith
  linarith [key]

/-- Finite groups satisfy the Følner condition (the whole group is invariant). -/
lemma folnerCond_of_finite [Finite Γ] : FolnerCond Γ := by
  haveI : Fintype Γ := Fintype.ofFinite Γ
  haveI : Nonempty Γ := ⟨1⟩
  intro K ε hε
  refine ⟨Finset.univ, Finset.univ_nonempty, fun g _ => ?_⟩
  have himg : (Finset.univ.image (g * ·) : Finset Γ) = Finset.univ :=
    Finset.eq_univ_of_forall fun x => Finset.mem_image.mpr ⟨g⁻¹ * x, Finset.mem_univ _, by group⟩
  simpa [lratio, himg] using hε

/-! ### Base case: cyclic groups -/

/-- **Cyclic groups satisfy the Følner condition.** For an infinite-order generator use the intervals
`{c⁰, …, cᵐ}`; for finite order the whole group works. -/
lemma folnerCond_of_isCyclic [IsCyclic Γ] : FolnerCond Γ := by
  obtain ⟨c, hgen⟩ := IsCyclic.exists_generator (α := Γ)
  intro K ε hε
  rcases eq_or_ne (orderOf c) 0 with hord | hord
  · -- infinite order: `i ↦ c ^ i` is injective
    have hinj : Function.Injective (fun i : ℤ => c ^ i) :=
      injective_zpow_iff_not_isOfFinOrder.mpr (by rwa [← orderOf_eq_zero_iff])
    have hex : ∀ k ∈ K, ∃ a : ℤ, (fun i : ℤ => c ^ i) a = k :=
      fun k _ => Subgroup.mem_zpowers_iff.mp (hgen k)
    choose! a ha using hex
    set A : ℕ := K.sup (fun k => (a k).natAbs) with hAdef
    obtain ⟨m, hm⟩ : ∃ m : ℕ, (A : ℝ) / (m + 1) < ε := by
      obtain ⟨m, hm⟩ := exists_nat_gt (A / ε)
      exact ⟨m, by rw [div_lt_iff₀ (by positivity)]; rw [div_lt_iff₀ hε] at hm; nlinarith [hm]⟩
    refine ⟨(Finset.Icc (0 : ℤ) m).image (fun i => c ^ i),
      (Finset.nonempty_Icc.mpr (by positivity)).image _, fun k hk => ?_⟩
    -- cardinality of the interval image
    have hcard : ((Finset.Icc (0 : ℤ) m).image (fun i => c ^ i)).card = m + 1 := by
      rw [Finset.card_image_of_injective _ hinj, Int.card_Icc]; simp
    -- `k · F = image of the shifted interval`
    have hak : c ^ (a k) = k := ha k hk
    have hshift : ((Finset.Icc (0 : ℤ) m).image (fun i => c ^ i)).image (k * ·)
        = (Finset.Icc (a k) (a k + m)).image (fun i => c ^ i) := by
      ext y
      simp only [Finset.mem_image, Finset.mem_Icc]
      constructor
      · rintro ⟨_, ⟨i, hi, rfl⟩, rfl⟩
        exact ⟨a k + i, ⟨by omega, by omega⟩, by rw [zpow_add, hak]⟩
      · rintro ⟨j, hj, rfl⟩
        refine ⟨c ^ (j - a k), ⟨j - a k, ⟨by omega, by omega⟩, rfl⟩, ?_⟩
        nth_rewrite 1 [← hak]
        rw [← zpow_add]; congr 1; omega
    -- injective image commutes with `\`
    have hsd : (Finset.Icc (a k) (a k + m)).image (fun i => c ^ i)
          \ (Finset.Icc (0 : ℤ) m).image (fun i => c ^ i)
        = (Finset.Icc (a k) (a k + m) \ Finset.Icc (0 : ℤ) m).image (fun i => c ^ i) := by
      ext y; simp only [Finset.mem_sdiff, Finset.mem_image]
      constructor
      · rintro ⟨⟨i, hi, rfl⟩, hn⟩
        exact ⟨i, ⟨hi, fun hi0 => hn ⟨i, hi0, rfl⟩⟩, rfl⟩
      · rintro ⟨i, ⟨hi, hni⟩, rfl⟩
        exact ⟨⟨i, hi, rfl⟩, fun ⟨j, hj, hji⟩ => hni (hinj hji ▸ hj)⟩
    -- the boundary is contained in an interval of length `|a k|`
    have hbdry : (Finset.Icc (a k) (a k + m) \ Finset.Icc (0 : ℤ) m).card ≤ (a k).natAbs := by
      rcases le_total 0 (a k) with hak | hak
      · refine le_trans (Finset.card_le_card (t := Finset.Icc ((m : ℤ) + 1) (a k + m))
          fun x hx => ?_) ?_
        · rw [Finset.mem_sdiff, Finset.mem_Icc, Finset.mem_Icc] at hx
          exact Finset.mem_Icc.mpr ⟨by omega, hx.1.2⟩
        · rw [Int.card_Icc]; omega
      · refine le_trans (Finset.card_le_card (t := Finset.Icc (a k) (-1)) fun x hx => ?_) ?_
        · rw [Finset.mem_sdiff, Finset.mem_Icc, Finset.mem_Icc] at hx
          exact Finset.mem_Icc.mpr ⟨hx.1.1, by omega⟩
        · rw [Int.card_Icc]; omega
    -- assemble the ratio bound
    rw [lratio, hshift, hsd, Finset.card_image_of_injective _ hinj, hcard,
      div_lt_iff₀ (by positivity)]
    have h1 : ((Finset.Icc (a k) (a k + m) \ Finset.Icc (0 : ℤ) m).card : ℝ) ≤ (A : ℝ) := by
      have hnat : (Finset.Icc (a k) (a k + m) \ Finset.Icc (0 : ℤ) m).card ≤ A :=
        le_trans hbdry (Finset.le_sup (f := fun k => (a k).natAbs) hk)
      exact_mod_cast hnat
    rw [div_lt_iff₀ (by positivity)] at hm
    push_cast at hm ⊢
    linarith [h1, hm]
  · -- finite order: `Γ` is finite, use `univ`
    have hfo : IsOfFinOrder c := orderOf_pos_iff.mp (Nat.pos_of_ne_zero hord)
    have hset : (Set.univ : Set Γ).Finite := hfo.finite_zpowers.subset fun x _ => hgen x
    haveI : Finite Γ := Set.finite_univ_iff.mp hset
    haveI : Fintype Γ := Fintype.ofFinite Γ
    haveI : Nonempty Γ := ⟨1⟩
    refine ⟨Finset.univ, Finset.univ_nonempty, fun g _ => ?_⟩
    have himg : (Finset.univ.image (g * ·) : Finset Γ) = Finset.univ :=
      Finset.eq_univ_of_forall fun x => Finset.mem_image.mpr ⟨g⁻¹ * x, Finset.mem_univ _, by group⟩
    simpa [lratio, himg] using hε

/-! ### Finitely generated abelian groups -/

/-- **Finitely generated abelian groups satisfy the Følner condition.** Induction on the number of
generators: `closure (insert a S')` surjects onto the cyclic group `A ⧸ closure S'` with kernel
`closure S'`, so `folnerCond_of_extension` combines the inductive hypothesis with the cyclic
base case. -/
private lemma folnerCond_comm_aux (n : ℕ) : ∀ {A : Type*} [CommGroup A] (S : Finset A),
    S.card ≤ n → Subgroup.closure (↑S : Set A) = ⊤ → FolnerCond A := by
  induction n with
  | zero =>
    intro A _ S hcard htop
    rw [Nat.le_zero, Finset.card_eq_zero] at hcard
    subst hcard
    rw [Finset.coe_empty, Subgroup.closure_empty] at htop
    haveI : Subsingleton A := ⟨fun x y => by
      have hx : x ∈ (⊥ : Subgroup A) := htop ▸ Subgroup.mem_top x
      have hy : y ∈ (⊥ : Subgroup A) := htop ▸ Subgroup.mem_top y
      rw [Subgroup.mem_bot] at hx hy; rw [hx, hy]⟩
    haveI : Finite A := Finite.of_subsingleton
    exact folnerCond_of_finite
  | succ n ih =>
    intro A _ S hcard htop
    rcases Finset.eq_empty_or_nonempty S with rfl | ⟨a, ha⟩
    · rw [Finset.coe_empty, Subgroup.closure_empty] at htop
      haveI : Subsingleton A := ⟨fun x y => by
        have hx : x ∈ (⊥ : Subgroup A) := htop ▸ Subgroup.mem_top x
        have hy : y ∈ (⊥ : Subgroup A) := htop ▸ Subgroup.mem_top y
        rw [Subgroup.mem_bot] at hx hy; rw [hx, hy]⟩
      haveI : Finite A := Finite.of_subsingleton
      exact folnerCond_of_finite
    · have hcard' : (S.erase a).card ≤ n := by
        have := Finset.card_erase_of_mem ha; omega
      -- inductive hypothesis: `FolnerCond` of the kernel subgroup
      have hNfol : FolnerCond (Subgroup.closure (↑(S.erase a) : Set A)) := by
        refine ih ((S.erase a).subtype (· ∈ Subgroup.closure (↑(S.erase a) : Set A))) ?_ ?_
        · rw [Finset.card_subtype]
          exact le_trans (Finset.card_filter_le _ _) hcard'
        · rw [eq_top_iff, ← Subgroup.closure_closure_coe_preimage (k := (↑(S.erase a) : Set A))]
          refine Subgroup.closure_mono fun x hx => ?_
          simp only [Set.mem_preimage, Finset.mem_coe, Finset.mem_subtype] at hx ⊢
          exact hx
      -- the quotient by that subgroup is cyclic (generated by the image of `a`)
      set N : Subgroup A := Subgroup.closure (↑(S.erase a) : Set A) with hNdef
      haveI hQcyc : IsCyclic (A ⧸ N) := by
        refine ⟨QuotientGroup.mk' N a, fun x => ?_⟩
        obtain ⟨b, rfl⟩ := QuotientGroup.mk'_surjective N x
        have hle : Subgroup.closure (↑S : Set A)
            ≤ (Subgroup.zpowers (QuotientGroup.mk' N a)).comap (QuotientGroup.mk' N) := by
          rw [Subgroup.closure_le]
          intro y hy
          rw [Finset.mem_coe] at hy
          rw [SetLike.mem_coe, Subgroup.mem_comap]
          by_cases hya : y = a
          · subst hya; exact Subgroup.mem_zpowers _
          · have : y ∈ N := Subgroup.subset_closure (Finset.mem_erase.mpr ⟨hya, hy⟩)
            rw [← QuotientGroup.ker_mk' N, MonoidHom.mem_ker] at this
            rw [this]; exact Subgroup.one_mem _
        rw [htop] at hle
        exact hle (Subgroup.mem_top b)
      rw [← QuotientGroup.ker_mk' N] at hNfol
      exact folnerCond_of_extension _ (QuotientGroup.mk'_surjective N) hNfol folnerCond_of_isCyclic

/-- Finitely generated abelian groups satisfy the Følner condition. -/
lemma folnerCond_of_comm_fg {A : Type*} [CommGroup A] (S : Finset A)
    (htop : Subgroup.closure (↑S : Set A) = ⊤) : FolnerCond A :=
  folnerCond_comm_aux S.card S le_rfl htop

/-- **General abelian groups satisfy the Følner condition** (reduce to the finitely generated
subgroup generated by the finite set at hand, then transport the Følner set out via `lratio_map`). -/
lemma folnerCond_of_comm {A : Type*} [CommGroup A] : FolnerCond A := by
  intro K ε hε
  have hfolH : FolnerCond ↥(Subgroup.closure (↑K : Set A)) := by
    apply folnerCond_of_comm_fg (K.subtype (· ∈ Subgroup.closure (↑K : Set A)))
    rw [eq_top_iff, ← Subgroup.closure_closure_coe_preimage (k := (↑K : Set A))]
    refine Subgroup.closure_mono fun x hx => ?_
    simp only [Set.mem_preimage, Finset.mem_coe, Finset.mem_subtype] at hx ⊢
    exact hx
  obtain ⟨FH, hFHne, hFH⟩ := hfolH (K.subtype (· ∈ Subgroup.closure (↑K : Set A))) hε
  refine ⟨FH.map ⟨(Subgroup.closure (↑K : Set A)).subtype, Subgroup.subtype_injective _⟩,
    hFHne.map, fun k hk => ?_⟩
  have hkH : k ∈ Subgroup.closure (↑K : Set A) := Subgroup.subset_closure hk
  calc lratio k (FH.map ⟨(Subgroup.closure (↑K : Set A)).subtype, Subgroup.subtype_injective _⟩)
      = lratio (⟨k, hkH⟩ : ↥(Subgroup.closure (↑K : Set A))) FH :=
        lratio_map (Subgroup.closure (↑K : Set A)).subtype (Subgroup.subtype_injective _) ⟨k, hkH⟩ FH
    _ < ε := hFH ⟨k, hkH⟩ (Finset.mem_subtype.mpr hk)

/-! ### Solvable groups -/

/-- The `m`-th derived subgroup of the commutator subgroup maps (via inclusion) to the `(m+1)`-th
derived subgroup of `G`. -/
private lemma derivedSeries_commutator_map {G : Type*} [Group G] (m : ℕ) :
    (derivedSeries (↥(commutator G)) m).map (commutator G).subtype = derivedSeries G (m + 1) := by
  induction m with
  | zero =>
    rw [derivedSeries_zero, ← MonoidHom.range_eq_map, Subgroup.range_subtype, derivedSeries_one]
  | succ k ihk => rw [derivedSeries_succ, Subgroup.map_commutator, ihk, ← derivedSeries_succ]

/-- Auxiliary induction on the length of the derived series. -/
private lemma folnerCond_solvable_aux (n : ℕ) : ∀ {G : Type*} [Group G],
    derivedSeries G n = ⊥ → FolnerCond G := by
  induction n with
  | zero =>
    intro G _ h
    rw [derivedSeries_zero] at h
    haveI : Subsingleton G := ⟨fun x y => by
      have hx : x ∈ (⊥ : Subgroup G) := h ▸ Subgroup.mem_top x
      have hy : y ∈ (⊥ : Subgroup G) := h ▸ Subgroup.mem_top y
      rw [Subgroup.mem_bot] at hx hy; rw [hx, hy]⟩
    haveI : Finite G := Finite.of_subsingleton
    exact folnerCond_of_finite
  | succ n ih =>
    intro G _ h
    -- the commutator subgroup is solvable of length `n`
    have hker : derivedSeries (↥(commutator G)) n = ⊥ := by
      have hmapbot : (derivedSeries (↥(commutator G)) n).map (commutator G).subtype = ⊥ := by
        rw [derivedSeries_commutator_map]; exact h
      rwa [Subgroup.map_eq_bot_iff, Subgroup.ker_subtype, le_bot_iff] at hmapbot
    have hNfol : FolnerCond ↥(commutator G) := ih hker
    -- glue with the abelian quotient `Abelianization G = G ⧸ commutator G`
    rw [← Abelianization.ker_of G] at hNfol
    exact folnerCond_of_extension Abelianization.of
      (QuotientGroup.mk'_surjective _) hNfol folnerCond_of_comm

/-- **Solvable groups satisfy the Følner condition.** -/
lemma folnerCond_of_isSolvable {G : Type*} [Group G] [IsSolvable G] : FolnerCond G := by
  obtain ⟨n, hn⟩ := IsSolvable.solvable (G := G)
  exact folnerCond_solvable_aux n hn

end UnitDistanceGraphs.Folner
