/-
[M23] Theorem 2 (as used in [DV26]): second blow-up.

Matolcsi–Ruzsa–Varga–Zsámboki (2023) show that the finitary fractional chromatic number of the plane
equals its Hall ratio, via a lattice construction. As explained in the introduction of [DV26],
the construction we actually need is the "second blow-up": from a finite unit-distance graph `V'`
with `χ_f(V') > 4`, taking a large discrete cube `A` in the additive lattice generated by `V(V')`
yields a finite unit-distance graph whose independence ratio is strictly below `1/4`.

The witness graph is the cube `A` itself. Its independence number is controlled by an *averaged
counting fractional coloring* of `V'` built from a maximum independent set `B ⊆ A`
(Part 1 below): every fractional coloring of `V'` has weight at least
`χ_f(V')`, and this particular one has weight `|V'−B| / |B|` with `|V'−B| ≤ (2(N+k)+1)^d`. Hence
`α(A) ≤ (2(N+k)+1)^d / χ_f(V')`, and dividing by `|A| = (2N+1)^d` gives
`α(A)/|A| ≤ (1/χ_f(V'))·((2(N+k)+1)/(2N+1))^d`, which is `< 1/4` for a large enough cube.

### On Layer 1 (the lattice basis)

From a finite vertex set `V' ⊆ ℂ`, the `ℤ`-span `M = span ℤ V'` is a finitely generated,
torsion-free `ℤ`-module, hence **free** with a finite basis `w : Fin d → ℂ`
(`Module.basisOfFiniteTypeTorsionFree'`). Along this basis every vertex `x ∈ V'` has *integer*
coordinates `coord x`, bounded in absolute value by a single `k`. This is exactly the coordinate
system in which [M23] builds the discrete cube `A = { ∑ βᵢ wᵢ : |βᵢ| ≤ N }` (Layer 2).
-/

import UnitDistanceGraphs.Definitions

namespace UnitDistanceGraphs

/-! ### Part 1 — the lattice-cube construction -/

section
open scoped BigOperators
open Classical
open Filter Topology

/-! ### L1: a `ℤ`-lattice basis for the span of the vertex set -/

/-- **L1 output.** A `ℤ`-lattice basis for the `ℤ`-span of the vertex set `V'`: `d` basis vectors
`w`, `ℤ`-linearly independent in `ℂ`, together with integer coordinates `coord x` reconstructing
each `x ∈ V'` and bounded in absolute value by `k`. -/
structure CubeBasis (V' : Finset ℂ) where
  /-- rank of the `ℤ`-span of `V'`. -/
  d : ℕ
  /-- the `d` basis vectors, as complex numbers. -/
  w : Fin d → ℂ
  /-- the basis vectors are `ℤ`-linearly independent in `ℂ`. -/
  windep : LinearIndependent ℤ w
  /-- integer coordinates of each point along the basis. -/
  coord : ℂ → Fin d → ℤ
  /-- a uniform bound on the absolute values of the coordinates of the vertices. -/
  k : ℕ
  /-- every vertex is reconstructed from its integer coordinates. -/
  repr : ∀ x ∈ V', ∑ i, (coord x i : ℂ) * w i = x
  /-- the coordinates of the vertices are bounded by `k`. -/
  bound : ∀ x ∈ V', ∀ i, (coord x i).natAbs ≤ k

/-- Every finite `V' ⊆ ℂ` admits a `CubeBasis`: the `ℤ`-span of `V'` is finitely generated and
torsion-free, hence free with a finite basis, along which each vertex has integer coordinates. -/
theorem exists_cubeBasis (V' : Finset ℂ) : Nonempty (CubeBasis V') := by
  classical
  set M : Submodule ℤ ℂ := Submodule.span ℤ (↑V' : Set ℂ) with hM
  haveI : Module.Finite ℤ M := Module.Finite.span_of_finite ℤ V'.finite_toSet
  obtain ⟨d, b⟩ := Module.basisOfFiniteTypeTorsionFree' (R := ℤ) (M := M)
  have hmem : ∀ x ∈ V', x ∈ M := fun x hx => Submodule.subset_span hx
  set w : Fin d → ℂ := fun i => (b i : ℂ) with hw
  set coord : ℂ → Fin d → ℤ :=
    fun x i => if hx : x ∈ M then b.repr ⟨x, hx⟩ i else 0 with hcoord
  refine ⟨{ d := d, w := w, coord := coord,
            k := V'.sup (fun x => Finset.univ.sup (fun i => (coord x i).natAbs)),
            windep := ?_, repr := ?_, bound := ?_ }⟩
  · -- `w = M.subtype ∘ b` is independent because `b` is and `M.subtype` is injective.
    exact b.linearIndependent.map' M.subtype (Submodule.ker_subtype M)
  · intro x hx
    have hxM : x ∈ M := hmem x hx
    have key : ((⟨x, hxM⟩ : M) : ℂ) = ∑ i, (b.repr ⟨x, hxM⟩ i : ℂ) * w i := by
      conv_lhs => rw [← b.sum_repr ⟨x, hxM⟩]
      rw [AddSubmonoidClass.coe_finsetSum]
      apply Finset.sum_congr rfl
      intro i _
      rw [SetLike.val_smul, hw, zsmul_eq_mul]
    simp only [hcoord, hxM, dif_pos]
    exact key.symm
  · intro x hx i
    have h1 : (coord x i).natAbs ≤ Finset.univ.sup (fun j => (coord x j).natAbs) :=
      Finset.le_sup (f := fun j => (coord x j).natAbs) (Finset.mem_univ i)
    have h2 : Finset.univ.sup (fun j => (coord x j).natAbs)
        ≤ V'.sup (fun y => Finset.univ.sup (fun j => (coord y j).natAbs)) :=
      Finset.le_sup (f := fun y => Finset.univ.sup (fun j => (coord y j).natAbs)) hx
    exact le_trans h1 h2

/-! ### L2: the discrete cube `A = { ∑ βᵢ wᵢ : |βᵢ| ≤ N }` -/

variable {V' : Finset ℂ}

/-- The linear-combination map of a `CubeBasis`: `β ↦ ∑ βᵢ wᵢ`. -/
def CubeBasis.phi (cb : CubeBasis V') (β : Fin cb.d → ℤ) : ℂ := ∑ i, (β i : ℂ) * cb.w i

/-- The lattice map `β ↦ ∑ βᵢ wᵢ` is injective, since the `wᵢ` are `ℤ`-linearly independent. -/
lemma CubeBasis.phi_injective (cb : CubeBasis V') : Function.Injective cb.phi := by
  intro β γ h
  have hzero : ∑ i, (β i - γ i) • cb.w i = 0 := by
    calc ∑ i, (β i - γ i) • cb.w i
        = ∑ i, ((β i : ℂ) * cb.w i - (γ i : ℂ) * cb.w i) := by
          apply Finset.sum_congr rfl; intro i _; rw [zsmul_eq_mul]; push_cast; ring
      _ = cb.phi β - cb.phi γ := by rw [Finset.sum_sub_distrib]; rfl
      _ = 0 := by rw [h, sub_self]
  have hcoef := Fintype.linearIndependent_iff.mp cb.windep (fun i => β i - γ i) hzero
  funext i; have := hcoef i; omega

/-- The **discrete cube** `A = { ∑ βᵢ wᵢ : βᵢ ∈ [-N, N] }` of the lattice, as a `Finset ℂ`. -/
noncomputable def CubeBasis.cube (cb : CubeBasis V') (N : ℕ) : Finset ℂ :=
  (Fintype.piFinset (fun _ : Fin cb.d => Finset.Icc (-(N : ℤ)) (N : ℤ))).image cb.phi

/-- **Cardinality of the cube:** `|A| = (2N+1)^d` (injectivity of the lattice map). -/
lemma CubeBasis.cube_card (cb : CubeBasis V') (N : ℕ) :
    (cb.cube N).card = (2 * N + 1) ^ cb.d := by
  rw [CubeBasis.cube, Finset.card_image_of_injective _ cb.phi_injective,
      Fintype.card_piFinset_const]
  have hIcc : (Finset.Icc (-(N : ℤ)) (N : ℤ)).card = 2 * N + 1 := by
    rw [Int.card_Icc]; omega
  rw [hIcc]

/-- **Coordinate/boundary control:** for `x ∈ V'` and `z` in the `N`-cube, the difference `x - z`
lies in the slightly larger `(N+k)`-cube. This is the key inclusion for bounding the difference
set `V' − B` in Layer 3. -/
lemma CubeBasis.sub_mem_cube (cb : CubeBasis V') {N : ℕ} {x : ℂ} (hx : x ∈ V')
    {z : ℂ} (hz : z ∈ cb.cube N) : x - z ∈ cb.cube (N + cb.k) := by
  rw [CubeBasis.cube, Finset.mem_image] at hz
  obtain ⟨β, hβ, rfl⟩ := hz
  rw [Fintype.mem_piFinset] at hβ
  rw [CubeBasis.cube, Finset.mem_image]
  refine ⟨fun i => cb.coord x i - β i, ?_, ?_⟩
  · rw [Fintype.mem_piFinset]
    intro i
    rw [Finset.mem_Icc]
    have hb := cb.bound x hx i
    have hβi := hβ i; rw [Finset.mem_Icc] at hβi
    omega
  · simp only [CubeBasis.phi]
    conv_rhs => rw [(cb.repr x hx).symm]
    rw [← Finset.sum_sub_distrib]
    apply Finset.sum_congr rfl
    intro i _
    push_cast; ring

/-! ### L3: a maximum independent set of the cube, and the difference-set bound -/

/-- The independence number of a nonempty graph is at least `1`. -/
lemma one_le_indepNum {V : Finset ℂ} (hV : V.Nonempty) : 1 ≤ indepNum V := by
  obtain ⟨v, hv⟩ := hV
  have hmem : ({v} : Finset ℂ) ∈ indepSets V := by
    rw [indepSets, Finset.mem_filter]
    refine ⟨Finset.mem_powerset.mpr (Finset.singleton_subset_iff.mpr hv), ?_⟩
    rw [Finset.coe_singleton, SimpleGraph.isIndepSet_iff]
    exact Set.pairwise_singleton _ _
  rw [indepNum]
  calc 1 = ({v} : Finset ℂ).card := (Finset.card_singleton v).symm
    _ ≤ (indepSets V).sup Finset.card := Finset.le_sup hmem

/-- The `sup` defining `indepNum` is attained: there is an independent set of maximum size. -/
lemma exists_max_indepSet {V : Finset ℂ} : ∃ B ∈ indepSets V, B.card = indepNum V := by
  have hne : (indepSets V).Nonempty := by
    refine ⟨∅, ?_⟩
    rw [indepSets, Finset.mem_filter]
    refine ⟨Finset.empty_mem_powerset V, ?_⟩
    rw [Finset.coe_empty, SimpleGraph.isIndepSet_iff]
    exact Set.pairwise_empty _
  obtain ⟨B, hB, hBcard⟩ := Finset.exists_mem_eq_sup (indepSets V) hne Finset.card
  exact ⟨B, hB, by rw [indepNum, hBcard]⟩

/-- The cube is nonempty (it contains `0 = ∑ 0·wᵢ`). -/
lemma CubeBasis.cube_nonempty (cb : CubeBasis V') (N : ℕ) : (cb.cube N).Nonempty := by
  refine ⟨cb.phi (fun _ => 0), ?_⟩
  rw [CubeBasis.cube, Finset.mem_image]
  refine ⟨fun _ => 0, ?_, rfl⟩
  rw [Fintype.mem_piFinset]; intro i; rw [Finset.mem_Icc]; omega

/-- **A maximum independent subset `B` of the cube `A`.** `B ⊆ A`, `B` is independent, has size
`α(A) = indepNum A`, and is nonempty. -/
lemma CubeBasis.exists_maxIndep (cb : CubeBasis V') (N : ℕ) :
    ∃ B : Finset ℂ, B ⊆ cb.cube N ∧ planeGraph.IsIndepSet (↑B : Set ℂ) ∧
      B.card = indepNum (cb.cube N) ∧ 1 ≤ B.card := by
  obtain ⟨B, hBmem, hBcard⟩ := exists_max_indepSet (V := cb.cube N)
  rw [indepSets, Finset.mem_filter, Finset.mem_powerset] at hBmem
  refine ⟨B, hBmem.1, hBmem.2, hBcard, ?_⟩
  rw [hBcard]
  exact one_le_indepNum (cb.cube_nonempty N)

/-- **Difference-set bound.** For `B ⊆ A` (the `N`-cube), the difference set `V' − B` fits inside the
`(N+k)`-cube, so `|V' − B| ≤ (2(N+k)+1)^d`. -/
lemma CubeBasis.diffSet_card_le (cb : CubeBasis V') {N : ℕ} {B : Finset ℂ}
    (hB : B ⊆ cb.cube N) :
    ((V' ×ˢ B).image (fun p => p.1 - p.2)).card ≤ (2 * (N + cb.k) + 1) ^ cb.d := by
  calc ((V' ×ˢ B).image (fun p => p.1 - p.2)).card
      ≤ (cb.cube (N + cb.k)).card := by
        apply Finset.card_le_card
        intro t ht
        rw [Finset.mem_image] at ht
        obtain ⟨⟨x, b⟩, hxb, rfl⟩ := ht
        rw [Finset.mem_product] at hxb
        exact cb.sub_mem_cube hxb.1 (hB hxb.2)
    _ = (2 * (N + cb.k) + 1) ^ cb.d := cb.cube_card (N + cb.k)

/-! ### L4: the averaged counting fractional coloring

Following [M23] Theorem 2: for a finite independent set `B` (the maximum independent set of the
cube), the *translate intersections* `M_t = V' ∩ (B + t) = { x ∈ V' : x − t ∈ B }` are independent
subsets of `V'`, and the averaged counting function `γ(S) = |{ t ∈ V'−B : M_t = S }| / |B|` is a
fractional coloring of `V'` of weight `|V'−B| / |B|`. -/

/-- The translate intersection `M_t = V' ∩ (B + t) = { x ∈ V' : x − t ∈ B }`. -/
noncomputable def transInter (V' B : Finset ℂ) (t : ℂ) : Finset ℂ :=
  V'.filter (fun x => x - t ∈ B)

/-- The difference set `V' − B = { x − b : x ∈ V', b ∈ B }`. -/
noncomputable def diffSet (V' B : Finset ℂ) : Finset ℂ :=
  (V' ×ˢ B).image (fun p => p.1 - p.2)

/-- The **averaged counting coloring** `γ(S) = |{ t ∈ V'−B : M_t = S }| / |B|`. -/
noncomputable def cntColoring (V' B : Finset ℂ) : Finset ℂ → ℝ :=
  fun S => (((diffSet V' B).filter (fun t => transInter V' B t = S)).card : ℝ) / (B.card : ℝ)

@[simp] lemma mem_transInter {V' B : Finset ℂ} {t x : ℂ} :
    x ∈ transInter V' B t ↔ x ∈ V' ∧ x - t ∈ B := by
  rw [transInter, Finset.mem_filter]

lemma mem_diffSet {V' B : Finset ℂ} {t : ℂ} :
    t ∈ diffSet V' B ↔ ∃ x ∈ V', ∃ b ∈ B, x - b = t := by
  simp only [diffSet, Finset.mem_image, Finset.mem_product, Prod.exists]
  constructor
  · rintro ⟨x, b, ⟨hx, hb⟩, rfl⟩; exact ⟨x, hx, b, hb, rfl⟩
  · rintro ⟨x, hx, b, hb, rfl⟩; exact ⟨x, b, ⟨hx, hb⟩, rfl⟩

/-- Each translate intersection is an independent subset of `V'` (translation preserves distances). -/
lemma transInter_indep {V' B : Finset ℂ} (hB : planeGraph.IsIndepSet (↑B : Set ℂ)) (t : ℂ) :
    planeGraph.IsIndepSet (↑(transInter V' B t) : Set ℂ) := by
  rw [SimpleGraph.isIndepSet_iff] at hB ⊢
  intro x hx y hy hxy
  rw [Finset.mem_coe, mem_transInter] at hx hy
  have hne : x - t ≠ y - t := by rw [ne_eq, sub_left_inj]; exact hxy
  have hnadj := hB (Finset.mem_coe.mpr hx.2) (Finset.mem_coe.mpr hy.2) hne
  intro hadj
  apply hnadj
  show dist (x - t) (y - t) = 1
  rw [dist_sub_right]
  exact hadj

/-- Each translate intersection lies in `indepSets V'`. -/
lemma transInter_mem_indepSets {V' B : Finset ℂ} (hB : planeGraph.IsIndepSet (↑B : Set ℂ)) (t : ℂ) :
    transInter V' B t ∈ indepSets V' := by
  rw [indepSets, Finset.mem_filter, Finset.mem_powerset]
  exact ⟨Finset.filter_subset _ _, transInter_indep hB t⟩

/-- **Weight of the counting coloring:** `∑_S γ(S) = |V'−B| / |B|`. -/
lemma cntColoring_weight {V' B : Finset ℂ} (hB : planeGraph.IsIndepSet (↑B : Set ℂ)) :
    weight V' (cntColoring V' B) = ((diffSet V' B).card : ℝ) / (B.card : ℝ) := by
  have H : Set.MapsTo (fun t => transInter V' B t) (diffSet V' B) (indepSets V') :=
    fun t _ => transInter_mem_indepSets hB t
  rw [weight]
  simp only [cntColoring]
  rw [← Finset.sum_div, ← Nat.cast_sum, ← Finset.card_eq_sum_card_fiberwise H]

/-- **Covering:** every vertex `x ∈ V'` is covered with total marginal exactly `1`. -/
lemma cntColoring_marginal {V' B : Finset ℂ} (hB : planeGraph.IsIndepSet (↑B : Set ℂ))
    (hBpos : 1 ≤ B.card) {x : ℂ} (hx : x ∈ V') :
    marginal V' (cntColoring V' B) {x} = 1 := by
  set s : Finset ℂ := (diffSet V' B).filter (fun t => x ∈ transInter V' B t) with hs
  -- (A) the fiber-count sum over the marginal's index set equals `|s|`.
  have HA : Set.MapsTo (fun t => transInter V' B t) s ((indepSets V').filter (fun S => {x} ⊆ S)) := by
    intro t ht
    simp only [hs, Finset.mem_coe, Finset.mem_filter, Finset.singleton_subset_iff] at ht ⊢
    exact ⟨transInter_mem_indepSets hB t, ht.2⟩
  have hA : ∑ S ∈ (indepSets V').filter (fun S => {x} ⊆ S),
      ((diffSet V' B).filter (fun t => transInter V' B t = S)).card = s.card := by
    rw [Finset.card_eq_sum_card_fiberwise HA]
    refine Finset.sum_congr rfl (fun S hS => ?_)
    rw [Finset.mem_filter, Finset.singleton_subset_iff] at hS
    congr 1
    rw [hs]
    ext t
    simp only [Finset.mem_filter]
    constructor
    · rintro ⟨htD, hTS⟩; exact ⟨⟨htD, by rw [hTS]; exact hS.2⟩, hTS⟩
    · rintro ⟨⟨htD, _⟩, hTS⟩; exact ⟨htD, hTS⟩
  -- (B) `|s| = |B|` via the bijection `b ↦ x − b`.
  have hB2 : s.card = B.card := by
    rw [hs]
    apply Finset.card_nbij' (fun t => x - t) (fun b => x - b)
    · intro t ht
      simp only [Finset.mem_coe, Finset.mem_filter, mem_transInter] at ht ⊢
      exact ht.2.2
    · intro b hb
      simp only [Finset.mem_coe, Finset.mem_filter, mem_diffSet, mem_transInter,
        sub_sub_cancel] at hb ⊢
      exact ⟨⟨x, hx, b, hb, rfl⟩, hx, hb⟩
    · intro t _; simp only [sub_sub_cancel]
    · intro b _; simp only [sub_sub_cancel]
  rw [marginal]
  simp only [cntColoring]
  rw [← Finset.sum_div, ← Nat.cast_sum, hA, hB2, div_self]
  exact Nat.cast_ne_zero.mpr (by omega)

/-- **The counting coloring is a fractional coloring of `V'`.** -/
lemma cntColoring_isColoring {V' B : Finset ℂ} (hB : planeGraph.IsIndepSet (↑B : Set ℂ))
    (hBpos : 1 ≤ B.card) : IsFractionalColoring V' (cntColoring V' B) where
  nonneg := fun S _ => by simp only [cntColoring]; positivity
  covers := fun x hx => (cntColoring_marginal hB hBpos hx).ge

/-! ### L5a: choosing a large enough cube (Archimedean step)

Since `(2(N+k)+1)/(2N+1) = 1 + 2k/(2N+1) → 1`, the boundary factor `((2(N+k)+1)/(2N+1))^d → 1`.
As `χ_f(V')/4 > 1`, some cube size `N` makes the factor drop below `χ_f(V')/4`. -/

/-- There is a cube size `N` for which the boundary blow-up factor is below `χ_f(V')/4`. -/
lemma exists_good_N (cb : CubeBasis V') (h : (4 : ℝ) < χ_f V') :
    ∃ N : ℕ, ((2 * ((N : ℝ) + cb.k) + 1) / (2 * (N : ℝ) + 1)) ^ cb.d < χ_f V' / 4 := by
  have htop : Tendsto (fun N : ℕ => (2 * (N : ℝ) + 1)) atTop atTop := by
    have h2 : Tendsto (fun N : ℕ => 2 * (N : ℝ)) atTop atTop :=
      Filter.Tendsto.const_mul_atTop (by norm_num) tendsto_natCast_atTop_atTop
    exact tendsto_atTop_add_const_right atTop 1 h2
  have hzero : Tendsto (fun N : ℕ => (2 * (cb.k : ℝ)) / (2 * (N : ℝ) + 1)) atTop (𝓝 0) :=
    htop.const_div_atTop (2 * (cb.k : ℝ))
  have hratio : Tendsto (fun N : ℕ => (2 * ((N : ℝ) + cb.k) + 1) / (2 * (N : ℝ) + 1)) atTop (𝓝 1) := by
    have heq : (fun N : ℕ => (2 * ((N : ℝ) + cb.k) + 1) / (2 * (N : ℝ) + 1))
             = (fun N : ℕ => 1 + (2 * (cb.k : ℝ)) / (2 * (N : ℝ) + 1)) := by
      funext N
      have hne : (2 * (N : ℝ) + 1) ≠ 0 := by positivity
      field_simp
      ring
    rw [heq]
    simpa using tendsto_const_nhds.add hzero
  have hpow : Tendsto (fun N : ℕ => ((2 * ((N : ℝ) + cb.k) + 1) / (2 * (N : ℝ) + 1)) ^ cb.d)
      atTop (𝓝 1) := by simpa using hratio.pow cb.d
  have hc : (1 : ℝ) < χ_f V' / 4 := by linarith
  exact (hpow.eventually_lt_const hc).exists

end

/-! ### Part 2 — assembly: `exists_low_independence_ratio` -/

section
open scoped BigOperators

/-- **[M23] Theorem 2 (consequence used here).** If a finite unit-distance graph `V'` has
fractional chromatic number greater than `4`, then there is a *nonempty* finite unit-distance
graph `H` with independence ratio strictly below `1/4`.
(The nonemptiness conjunct rules out the vacuous witness `H = ∅`, whose independence ratio is
`0/0 = 0` under Lean's division convention.)

This packages the lattice-cube/second-blow-up argument: the independence ratio of the discrete
cube `A` in the lattice generated by `V'` is at most `(1/χ_f(V'))·((2(N+k)+1)/(2N+1))^d`, which is
`< 1/4` once `χ_f(V') > 4` and the cube is large. -/
theorem exists_low_independence_ratio (V' : UnitDistanceGraph) (h : (4 : ℝ) < χ_f V') :
    ∃ H : UnitDistanceGraph, H.Nonempty ∧ independenceRatio H < 1 / 4 := by
  classical
  obtain ⟨cb⟩ := exists_cubeBasis V'
  obtain ⟨N, hN⟩ := exists_good_N cb h
  refine ⟨cb.cube N, cb.cube_nonempty N, ?_⟩
  obtain ⟨B, hBsub, hBindep, hBcard, hBpos⟩ := cb.exists_maxIndep N
  -- Every fractional coloring of `V'` has weight `≥ χ_f V'`; our counting coloring has weight
  -- `|V'−B| / |B|`.
  have hbdd : BddBelow {w | ∃ γ, IsFractionalColoring V' γ ∧ weight V' γ = w} :=
    ⟨0, fun w hw => by
      obtain ⟨δ, hδ, rfl⟩ := hw
      exact Finset.sum_nonneg (fun S hS => hδ.nonneg S hS)⟩
  have hle : χ_f V' ≤ weight V' (cntColoring V' B) :=
    csInf_le hbdd ⟨_, cntColoring_isColoring hBindep hBpos, rfl⟩
  rw [cntColoring_weight hBindep] at hle
  -- Real bookkeeping.
  have hBpos' : (0 : ℝ) < (B.card : ℝ) := by exact_mod_cast hBpos
  have hχ0 : (0 : ℝ) < χ_f V' := by linarith
  have hdiff : ((diffSet V' B).card : ℝ) ≤ (2 * ((N : ℝ) + cb.k) + 1) ^ cb.d := by
    exact_mod_cast cb.diffSet_card_le hBsub
  have hkey : χ_f V' * (B.card : ℝ) ≤ (2 * ((N : ℝ) + cb.k) + 1) ^ cb.d :=
    le_trans ((le_div_iff₀ hBpos').mp hle) hdiff
  -- `(2(N+k)+1)^d = (2N+1)^d · ((2(N+k)+1)/(2N+1))^d`.
  have hne : ((2 * (N : ℝ) + 1) ^ cb.d) ≠ 0 := by positivity
  have hR : (2 * ((N : ℝ) + cb.k) + 1) ^ cb.d
      = (2 * (N : ℝ) + 1) ^ cb.d * ((2 * ((N : ℝ) + cb.k) + 1) / (2 * (N : ℝ) + 1)) ^ cb.d := by
    rw [div_pow, mul_comm ((2 * (N : ℝ) + 1) ^ cb.d), div_mul_cancel₀ _ hne]
  have hPpos : (0 : ℝ) < (2 * (N : ℝ) + 1) ^ cb.d := by positivity
  rw [hR] at hkey
  -- `4·|B| < (2N+1)^d`, hence `α(A)/|A| < 1/4`.
  have hgoalR : 4 * (B.card : ℝ) < (2 * (N : ℝ) + 1) ^ cb.d := by
    nlinarith [hkey, hN, hPpos, hχ0, hBpos', mul_lt_mul_of_pos_left hN hPpos]
  have hnat : 4 * B.card < (2 * N + 1) ^ cb.d := by exact_mod_cast hgoalR
  have hPℚ : (0 : ℚ) < ((2 * N + 1) ^ cb.d : ℕ) := by positivity
  rw [independenceRatio, show indepNum (cb.cube N) = B.card from hBcard.symm, cb.cube_card N,
      div_lt_iff₀ hPℚ]
  have hq : (4 * B.card : ℚ) < ((2 * N + 1) ^ cb.d : ℕ) := by exact_mod_cast hnat
  linarith [hq]

end

end UnitDistanceGraphs
